# Generated by Django 2.2.10 on 2020-03-10 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('year', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=10, null=True)),
                ('section', models.CharField(blank=True, choices=[('Section A', 'Section A'), ('Section B', 'Section B'), ('Section C', 'Section C'), ('Section D', 'Section D')], max_length=10, null=True)),
                ('branch', models.CharField(blank=True, choices=[('M.C.A', 'M.C.A'), ('M.B.A', 'M.B.A'), ('E.C.E', 'E.C.E'), ('E.E.E', 'E.E.E'), ('C.S.E', 'C.S.E'), ('IT', 'IT'), ('CIVIL', 'CIVIL')], max_length=10, null=True)),
                ('phone', models.IntegerField(blank=True, null=True, unique=True)),
                ('rollnumber', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('datejoined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('subject', models.CharField(max_length=300)),
                ('question', models.TextField(max_length=5000)),
                ('Option1', models.CharField(max_length=1000)),
                ('Option2', models.CharField(max_length=1000)),
                ('Option3', models.CharField(max_length=1000)),
                ('Option4', models.CharField(max_length=1000)),
                ('option', models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('rollnumber', models.CharField(max_length=225)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
