# Generated by Django 2.2.10 on 2020-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_comments',
            name='message',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='student_comments',
            name='subject',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_comments',
            name='message',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='user_comments',
            name='subject',
            field=models.CharField(max_length=3000),
        ),
    ]
