# Generated by Django 2.2.10 on 2020-03-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0003_auto_20200313_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
