# Generated by Django 2.2.10 on 2020-03-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0006_auto_20200324_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
