# Generated by Django 2.2.10 on 2020-04-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0010_auto_20200331_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(choices=[('#007bff', '#007bff'), ('#EC407A', '#EC407A'), ('#FF5733', '#FF5733'), ('#2ECC71', '#2ECC71'), ('#7D3C98', '#7D3C98'), ('#1B4F72', '#1B4F72'), ('#F7DC6', '#F7DC6')], max_length=100),
        ),
    ]
