# Generated by Django 2.2.10 on 2020-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0011_auto_20200404_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Question'),
        ),
    ]
