# Generated by Django 2.2.10 on 2020-04-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0012_auto_20200404_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
    ]
