# Generated by Django 2.2.10 on 2020-04-06 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0014_auto_20200406_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_pic',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
