# Generated by Django 2.2.10 on 2020-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0016_auto_20200406_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(max_length=255, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Profile_pic',
        ),
    ]
