# Generated by Django 2.2.10 on 2020-04-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0017_auto_20200406_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank='True', max_length=255, null=True, upload_to=''),
        ),
    ]
