# Generated by Django 2.2.10 on 2020-04-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svapp', '0020_auto_20200407_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picture',
            new_name='image',
        ),
    ]
